### ISSUE TITLE
Shareberry queuing songs twice.

### ISSUE THREAD

**Issue by FluidExtractor** [raveberry/shareberry#3]
Sharing a YouTube video to Shareberry makes it queue twice on Raveberry. Happens with Shareberry configured to http://raveberry  or http://ip

**Comment by raveberry** [comment]
I just tried it out and it only queued the song once, even with multiple entries for the same device in Shareberry.

Are you sharing from the YouTube app? Do you have Spotify enabled?

**Comment by FluidExtractor** [comment]
I'm either going crazy, or my raveberry install was broken in some way. After today's Raveberry update, songs are no longer being queued twice.
Sorry for wasting your time.

**Comment by raveberry** [comment]
I encountered this issue occasionally, but could never reproduce it until recently. The problem was that Volley (the library used to do the requests) actually [performs the post twice sometimes](https://stackoverflow.com/questions/22428343/android-volley-double-post-when-have-slow-request).
This happens when the response takes too long, which can sometimes be the case on the Raspberry Pi. With v0.1.2 this issue was fixed in Shareberry.
